# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(309, 138)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Dt = QtWidgets.QLabel(Form)
        self.label_Dt.setObjectName("label_Dt")
        self.gridLayout.addWidget(self.label_Dt, 0, 0, 1, 1)
        self.lineEdit_Dt = QtWidgets.QLineEdit(Form)
        self.lineEdit_Dt.setObjectName("lineEdit_Dt")
        self.gridLayout.addWidget(self.lineEdit_Dt, 0, 1, 1, 2)
        self.btnSave = QtWidgets.QPushButton(Form)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 1, 0, 1, 2)
        self.btnCancel = QtWidgets.QPushButton(Form)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_Dt.setText(_translate("Form", "Time window:"))
        self.btnSave.setText(_translate("Form", "Save"))
        self.btnCancel.setText(_translate("Form", "Cancel"))
