# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters_dialog_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(297, 159)
        Dialog.setMinimumSize(QtCore.QSize(250, 150))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Dt = QtWidgets.QLabel(Dialog)
        self.label_Dt.setObjectName("label_Dt")
        self.gridLayout.addWidget(self.label_Dt, 0, 0, 1, 1)
        self.lineEdit_Dt = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Dt.setObjectName("lineEdit_Dt")
        self.gridLayout.addWidget(self.lineEdit_Dt, 0, 1, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 1, 0, 1, 1)
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_Dt.setText(_translate("Dialog", "Time window:"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
        self.btnSave.setText(_translate("Dialog", "Save"))
